package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbAdmMenusxpermisos generated by hbm2java
 */
public class TbAdmMenusxpermisos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbAdmMenus tbAdmMenus;
     private TbAdmPermisos tbAdmPermisos;
     private String vrAdtusuario;
     private Date dtAdtfecha;

    public TbAdmMenusxpermisos() {
    }

    public TbAdmMenusxpermisos(TbAdmMenus tbAdmMenus, TbAdmPermisos tbAdmPermisos, String vrAdtusuario, Date dtAdtfecha) {
       this.tbAdmMenus = tbAdmMenus;
       this.tbAdmPermisos = tbAdmPermisos;
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbAdmMenus getTbAdmMenus() {
        return this.tbAdmMenus;
    }
    
    public void setTbAdmMenus(TbAdmMenus tbAdmMenus) {
        this.tbAdmMenus = tbAdmMenus;
    }
    public TbAdmPermisos getTbAdmPermisos() {
        return this.tbAdmPermisos;
    }
    
    public void setTbAdmPermisos(TbAdmPermisos tbAdmPermisos) {
        this.tbAdmPermisos = tbAdmPermisos;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }




}


