package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbAdmDropdowns generated by hbm2java
 */
public class TbAdmDropdowns  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     private String vrNombre;
     private String vrDescripcion;
     private String vrValor;

    public TbAdmDropdowns() {
    }

    public TbAdmDropdowns(String vrAdtusuario, Date dtAdtfecha, String vrNombre, String vrDescripcion, String vrValor) {
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
       this.vrNombre = vrNombre;
       this.vrDescripcion = vrDescripcion;
       this.vrValor = vrValor;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
    public String getVrNombre() {
        return this.vrNombre;
    }
    
    public void setVrNombre(String vrNombre) {
        this.vrNombre = vrNombre;
    }
    public String getVrDescripcion() {
        return this.vrDescripcion;
    }
    
    public void setVrDescripcion(String vrDescripcion) {
        this.vrDescripcion = vrDescripcion;
    }
    public String getVrValor() {
        return this.vrValor;
    }
    
    public void setVrValor(String vrValor) {
        this.vrValor = vrValor;
    }




}


