package co.edu.udea.proyectointegrador.dto;
// Generated Oct 10, 2013 10:28:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbAdmUsuarios generated by hbm2java
 */
public class TbAdmUsuarios  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbAdmRoles tbAdmRoles;
     private String vrUsuario;
     private String vrNombres;
     private String vrApellidos;
     private String vrCorreo;
     private int nbEstado;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     private String vrUniversidad;
     private String vrClave;
     private String vrCedula;
     
     public String getVrClave() {
		return vrClave;
	}


	public void setVrClave(String vrClave) {
		this.vrClave = vrClave;
	}


	public String getVrCedula() {
		return vrCedula;
	}


	public void setVrCedula(String vrCedula) {
		this.vrCedula = vrCedula;
	}


	
    public TbAdmUsuarios() {
    }

	
    public TbAdmUsuarios(TbAdmRoles tbAdmRoles, String vrUsuario, String vrNombres, String vrApellidos, String vrCorreo, int nbEstado, String vrAdtusuario, Date dtAdtfecha, String vrUniversidad) {
        this.tbAdmRoles = tbAdmRoles;
        this.vrUsuario = vrUsuario;
        this.vrNombres = vrNombres;
        this.vrApellidos = vrApellidos;
        this.vrCorreo = vrCorreo;
        this.nbEstado = nbEstado;
        this.vrAdtusuario = vrAdtusuario;
        this.dtAdtfecha = dtAdtfecha;
        this.vrUniversidad = vrUniversidad;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbAdmRoles getTbAdmRoles() {
        return this.tbAdmRoles;
    }
    
    public void setTbAdmRoles(TbAdmRoles tbAdmRoles) {
        this.tbAdmRoles = tbAdmRoles;
    }
    public String getVrUsuario() {
        return this.vrUsuario;
    }
    
    public void setVrUsuario(String vrUsuario) {
        this.vrUsuario = vrUsuario;
    }
    public String getVrNombres() {
        return this.vrNombres;
    }
    
    public void setVrNombres(String vrNombres) {
        this.vrNombres = vrNombres;
    }
    public String getVrApellidos() {
        return this.vrApellidos;
    }
    
    public void setVrApellidos(String vrApellidos) {
        this.vrApellidos = vrApellidos;
    }
    public String getVrCorreo() {
        return this.vrCorreo;
    }
    
    public void setVrCorreo(String vrCorreo) {
        this.vrCorreo = vrCorreo;
    }
    public int getNbEstado() {
        return this.nbEstado;
    }
    
    public void setNbEstado(int nbEstado) {
        this.nbEstado = nbEstado;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
    public String getVrUniversidad() {
        return this.vrUniversidad;
    }
    
    public void setVrUniversidad(String vrUniversidad) {
        this.vrUniversidad = vrUniversidad;
    }


}


