package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmMenus generated by hbm2java
 */
public class TbAdmMenus  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     private String vrNombre;
     private String vrDescripcion;
     private String vrUrl;
     private int nbPosicion;
     private Set<TbAdmMenusxpermisos> tbAdmMenusxpermisoses = new HashSet<TbAdmMenusxpermisos>(0);

    public TbAdmMenus() {
    }

	
    public TbAdmMenus(String vrAdtusuario, Date dtAdtfecha, String vrNombre, String vrDescripcion, String vrUrl, int nbPosicion) {
        this.vrAdtusuario = vrAdtusuario;
        this.dtAdtfecha = dtAdtfecha;
        this.vrNombre = vrNombre;
        this.vrDescripcion = vrDescripcion;
        this.vrUrl = vrUrl;
        this.nbPosicion = nbPosicion;
    }
    public TbAdmMenus(String vrAdtusuario, Date dtAdtfecha, String vrNombre, String vrDescripcion, String vrUrl, int nbPosicion, Set<TbAdmMenusxpermisos> tbAdmMenusxpermisoses) {
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
       this.vrNombre = vrNombre;
       this.vrDescripcion = vrDescripcion;
       this.vrUrl = vrUrl;
       this.nbPosicion = nbPosicion;
       this.tbAdmMenusxpermisoses = tbAdmMenusxpermisoses;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
    public String getVrNombre() {
        return this.vrNombre;
    }
    
    public void setVrNombre(String vrNombre) {
        this.vrNombre = vrNombre;
    }
    public String getVrDescripcion() {
        return this.vrDescripcion;
    }
    
    public void setVrDescripcion(String vrDescripcion) {
        this.vrDescripcion = vrDescripcion;
    }
    public String getVrUrl() {
        return this.vrUrl;
    }
    
    public void setVrUrl(String vrUrl) {
        this.vrUrl = vrUrl;
    }
    public int getNbPosicion() {
        return this.nbPosicion;
    }
    
    public void setNbPosicion(int nbPosicion) {
        this.nbPosicion = nbPosicion;
    }
    public Set<TbAdmMenusxpermisos> getTbAdmMenusxpermisoses() {
        return this.tbAdmMenusxpermisoses;
    }
    
    public void setTbAdmMenusxpermisoses(Set<TbAdmMenusxpermisos> tbAdmMenusxpermisoses) {
        this.tbAdmMenusxpermisoses = tbAdmMenusxpermisoses;
    }




}


