package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbAdmRolesxpermisos generated by hbm2java
 */
public class TbAdmRolesxpermisos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbAdmPermisos tbAdmPermisos;
     private TbAdmRoles tbAdmRoles;
     private String vrAdtusuario;
     private Date dtAdtfecha;

    public TbAdmRolesxpermisos() {
    }

    public TbAdmRolesxpermisos(TbAdmPermisos tbAdmPermisos, TbAdmRoles tbAdmRoles, String vrAdtusuario, Date dtAdtfecha) {
       this.tbAdmPermisos = tbAdmPermisos;
       this.tbAdmRoles = tbAdmRoles;
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbAdmPermisos getTbAdmPermisos() {
        return this.tbAdmPermisos;
    }
    
    public void setTbAdmPermisos(TbAdmPermisos tbAdmPermisos) {
        this.tbAdmPermisos = tbAdmPermisos;
    }
    public TbAdmRoles getTbAdmRoles() {
        return this.tbAdmRoles;
    }
    
    public void setTbAdmRoles(TbAdmRoles tbAdmRoles) {
        this.tbAdmRoles = tbAdmRoles;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }




}


