package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbAdmConfiguraciones generated by hbm2java
 */
public class TbAdmConfiguraciones  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     private String vrClave;
     private String vrValor;

    public TbAdmConfiguraciones() {
    }

    public TbAdmConfiguraciones(String vrAdtusuario, Date dtAdtfecha, String vrClave, String vrValor) {
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
       this.vrClave = vrClave;
       this.vrValor = vrValor;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
    public String getVrClave() {
        return this.vrClave;
    }
    
    public void setVrClave(String vrClave) {
        this.vrClave = vrClave;
    }
    public String getVrValor() {
        return this.vrValor;
    }
    
    public void setVrValor(String vrValor) {
        this.vrValor = vrValor;
    }




}


