package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbNtfMediostipontf generated by hbm2java
 */
public class TbNtfMediostipontf  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbNtfMediosntf tbNtfMediosntf;
     private TbNtfTipontfs tbNtfTipontfs;
     private boolean blConfigurable;
     private String vrAdtusuario;
     private Date dtAdtfecha;
    
    public TbNtfMediostipontf() {
    }

	
    public TbNtfMediostipontf(TbNtfMediosntf tbNtfMediosntf, TbNtfTipontfs tbNtfTipontfs, boolean blConfigurable, String vrAdtusuario, Date dtAdtfecha) {
        this.tbNtfMediosntf = tbNtfMediosntf;
        this.tbNtfTipontfs = tbNtfTipontfs;
        this.blConfigurable = blConfigurable;
        this.vrAdtusuario = vrAdtusuario;
        this.dtAdtfecha = dtAdtfecha;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbNtfMediosntf getTbNtfMediosntf() {
        return this.tbNtfMediosntf;
    }
    
    public void setTbNtfMediosntf(TbNtfMediosntf tbNtfMediosntf) {
        this.tbNtfMediosntf = tbNtfMediosntf;
    }
    public TbNtfTipontfs getTbNtfTipontfs() {
        return this.tbNtfTipontfs;
    }
    
    public void setTbNtfTipontfs(TbNtfTipontfs tbNtfTipontfs) {
        this.tbNtfTipontfs = tbNtfTipontfs;
    }
    public boolean isBlConfigurable() {
        return this.blConfigurable;
    }
    
    public void setBlConfigurable(boolean blConfigurable) {
        this.blConfigurable = blConfigurable;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
   


}


