package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbNtfNtfsxusuario generated by hbm2java
 */
public class TbNtfNtfsxusuario  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbNtfNotificaciones tbNtfNotificaciones;
     private TbAdmUsuarios tbAdmUsuarios;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     private boolean blNotificada;

    public TbNtfNtfsxusuario() {
    }

    public TbNtfNtfsxusuario(TbNtfNotificaciones tbNtfNotificaciones, TbAdmUsuarios tbAdmUsuarios, String vrAdtusuario, Date dtAdtfecha, boolean blNotificada) {
       this.tbNtfNotificaciones = tbNtfNotificaciones;
       this.tbAdmUsuarios = tbAdmUsuarios;
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
       this.blNotificada = blNotificada;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbNtfNotificaciones getTbNtfNotificaciones() {
        return this.tbNtfNotificaciones;
    }
    
    public void setTbNtfNotificaciones(TbNtfNotificaciones tbNtfNotificaciones) {
        this.tbNtfNotificaciones = tbNtfNotificaciones;
    }
    public TbAdmUsuarios getTbAdmUsuarios() {
        return this.tbAdmUsuarios;
    }
    
    public void setTbAdmUsuarios(TbAdmUsuarios tbAdmUsuarios) {
        this.tbAdmUsuarios = tbAdmUsuarios;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
    public boolean isBlNotificada() {
        return this.blNotificada;
    }
    
    public void setBlNotificada(boolean blNotificada) {
        this.blNotificada = blNotificada;
    }




}


