package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbNtfUsrtpntfmedios generated by hbm2java
 */
public class TbNtfUsrtpntfmedios  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbNtfMediostipontf tbNtfMediostipontf;
     private TbNtfUsuariostipontf tbNtfUsuariostipontf;
     private boolean blNotificar;
     private String vrAdtusuario;
     private Date dtAdtfecha;

    public TbNtfUsrtpntfmedios() {
    }

    public TbNtfUsrtpntfmedios(TbNtfMediostipontf tbNtfMediostipontf, TbNtfUsuariostipontf tbNtfUsuariostipontf, boolean blNotificar, String vrAdtusuario, Date dtAdtfecha) {
       this.tbNtfMediostipontf = tbNtfMediostipontf;
       this.tbNtfUsuariostipontf = tbNtfUsuariostipontf;
       this.blNotificar = blNotificar;
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbNtfMediostipontf getTbNtfMediostipontf() {
        return this.tbNtfMediostipontf;
    }
    
    public void setTbNtfMediostipontf(TbNtfMediostipontf tbNtfMediostipontf) {
        this.tbNtfMediostipontf = tbNtfMediostipontf;
    }
    public TbNtfUsuariostipontf getTbNtfUsuariostipontf() {
        return this.tbNtfUsuariostipontf;
    }
    
    public void setTbNtfUsuariostipontf(TbNtfUsuariostipontf tbNtfUsuariostipontf) {
        this.tbNtfUsuariostipontf = tbNtfUsuariostipontf;
    }
    public boolean isBlNotificar() {
        return this.blNotificar;
    }
    
    public void setBlNotificar(boolean blNotificar) {
        this.blNotificar = blNotificar;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }




}


