package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbNtfNotificaciones generated by hbm2java
 */
public class TbNtfNotificaciones  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbNtfTipontfs tbNtfTipontfs;
     private String vrAsunto;
     private String vrMensaje;
     private Date dtFecha;
     private String vrAdtusuario;
     private Date dtAdtfecha;
  
    public TbNtfNotificaciones() {
    }

	
    public TbNtfNotificaciones(TbNtfTipontfs tbNtfTipontfs, String vrAsunto, String vrMensaje, Date dtFecha, String vrAdtusuario, Date dtAdtfecha) {
        this.tbNtfTipontfs = tbNtfTipontfs;
        this.vrAsunto = vrAsunto;
        this.vrMensaje = vrMensaje;
        this.dtFecha = dtFecha;
        this.vrAdtusuario = vrAdtusuario;
        this.dtAdtfecha = dtAdtfecha;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbNtfTipontfs getTbNtfTipontfs() {
        return this.tbNtfTipontfs;
    }
    
    public void setTbNtfTipontfs(TbNtfTipontfs tbNtfTipontfs) {
        this.tbNtfTipontfs = tbNtfTipontfs;
    }
    public String getVrAsunto() {
        return this.vrAsunto;
    }
    
    public void setVrAsunto(String vrAsunto) {
        this.vrAsunto = vrAsunto;
    }
    public String getVrMensaje() {
        return this.vrMensaje;
    }
    
    public void setVrMensaje(String vrMensaje) {
        this.vrMensaje = vrMensaje;
    }
    public Date getDtFecha() {
        return this.dtFecha;
    }
    
    public void setDtFecha(Date dtFecha) {
        this.dtFecha = dtFecha;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
  



}


