package co.edu.udea.proyectointegrador.dto;
// Generated Jan 22, 2014 7:26:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryArchivoxentregable generated by hbm2java
 */
public class TbPryArchivoxentregable  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 4695371103147930195L;
	private Integer nbIdn;
     private TbPryEntregablexactividad tbPryEntregablexactividad;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     private String vrNombre;
     private byte[] blobAdjunto;
     private String vrComentarioparticipante;
     private String vrComentarioasesor;

    public TbPryArchivoxentregable() {
    }

	
    public TbPryArchivoxentregable(Integer nbIdn, TbPryEntregablexactividad tbPryEntregablexactividad, String vrAdtusuario, Date dtAdtfecha, String vrNombre, byte[] blobAdjunto, String vrComentarioparticipante) {
        this.nbIdn = nbIdn;
        this.tbPryEntregablexactividad = tbPryEntregablexactividad;
        this.vrAdtusuario = vrAdtusuario;
        this.dtAdtfecha = dtAdtfecha;
        this.vrNombre = vrNombre;
        this.blobAdjunto = blobAdjunto;
        this.vrComentarioparticipante = vrComentarioparticipante;
    }
    public TbPryArchivoxentregable(Integer nbIdn, TbPryEntregablexactividad tbPryEntregablexactividad, String vrAdtusuario, Date dtAdtfecha, String vrNombre, byte[] blobAdjunto, String vrComentarioparticipante, String vrComentarioasesor) {
       this.nbIdn = nbIdn;
       this.tbPryEntregablexactividad = tbPryEntregablexactividad;
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
       this.vrNombre = vrNombre;
       this.blobAdjunto = blobAdjunto;
       this.vrComentarioparticipante = vrComentarioparticipante;
       this.vrComentarioasesor = vrComentarioasesor;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbPryEntregablexactividad getTbPryEntregablexactividad() {
        return this.tbPryEntregablexactividad;
    }
    
    public void setTbPryEntregablexactividad(TbPryEntregablexactividad tbPryEntregablexactividad) {
        this.tbPryEntregablexactividad = tbPryEntregablexactividad;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
    public String getVrNombre() {
        return this.vrNombre;
    }
    
    public void setVrNombre(String vrNombre) {
        this.vrNombre = vrNombre;
    }
    public byte[] getBlobAdjunto() {
        return this.blobAdjunto;
    }
    
    public void setBlobAdjunto(byte[] blobAdjunto) {
        this.blobAdjunto = blobAdjunto;
    }
    public String getVrComentarioparticipante() {
        return this.vrComentarioparticipante;
    }
    
    public void setVrComentarioparticipante(String vrComentarioparticipante) {
        this.vrComentarioparticipante = vrComentarioparticipante;
    }
    public String getVrComentarioasesor() {
        return this.vrComentarioasesor;
    }
    
    public void setVrComentarioasesor(String vrComentarioasesor) {
        this.vrComentarioasesor = vrComentarioasesor;
    }




}


