package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryParticipantexactividad generated by hbm2java
 */
public class TbPryParticipantexactividad  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbPryActividades tbPryActividades;
     private TbAdmUsuarios tbAdmUsuarios;
     private String vrAdtusuario;
     private Date dtAdtfecha;

    public TbPryParticipantexactividad() {
    }

    public TbPryParticipantexactividad(TbPryActividades tbPryActividades, TbAdmUsuarios tbAdmUsuarios, String vrAdtusuario, Date dtAdtfecha) {
       this.tbPryActividades = tbPryActividades;
       this.tbAdmUsuarios = tbAdmUsuarios;
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbPryActividades getTbPryActividades() {
        return this.tbPryActividades;
    }
    
    public void setTbPryActividades(TbPryActividades tbPryActividades) {
        this.tbPryActividades = tbPryActividades;
    }
    public TbAdmUsuarios getTbAdmUsuarios() {
        return this.tbAdmUsuarios;
    }
    
    public void setTbAdmUsuarios(TbAdmUsuarios tbAdmUsuarios) {
        this.tbAdmUsuarios = tbAdmUsuarios;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }




}


