package co.edu.udea.proyectointegrador.dto;

import java.util.Date;
// Generated Oct 10, 2013 10:28:13 AM by Hibernate Tools 3.2.1.GA



/**
 * TbPryRolesxpermisosestadosactividad generated by hbm2java
 */
public class TbPryRolesxpermisosestadosactividad  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbPryPermisosxestadosactividad tbPryPermisosxestadosactividad;
     private TbAdmRoles tbAdmRoles;

     private String vrAdtusuario;
     private Date dtAdtfecha;
     
    public String getVrAdtusuario() {
		return vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPryRolesxpermisosestadosactividad() {
    }

    public TbPryRolesxpermisosestadosactividad(Integer nbIdn, TbPryPermisosxestadosactividad tbPryPermisosxestadosactividad, TbAdmRoles tbAdmRoles) {
       this.nbIdn = nbIdn;
       this.tbPryPermisosxestadosactividad = tbPryPermisosxestadosactividad;
       this.tbAdmRoles = tbAdmRoles;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbPryPermisosxestadosactividad getTbPryPermisosxestadosactividad() {
        return this.tbPryPermisosxestadosactividad;
    }
    
    public void setTbPryPermisosxestadosactividad(TbPryPermisosxestadosactividad tbPryPermisosxestadosactividad) {
        this.tbPryPermisosxestadosactividad = tbPryPermisosxestadosactividad;
    }
    public TbAdmRoles getTbAdmRoles() {
        return this.tbAdmRoles;
    }
    
    public void setTbAdmRoles(TbAdmRoles tbAdmRoles) {
        this.tbAdmRoles = tbAdmRoles;
    }




}


