package co.edu.udea.proyectointegrador.dto;

import java.util.Date;
// Generated Nov 5, 2013 7:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * TbPryActividadesxactividades generated by hbm2java
 */
public class TbPryActividadesxactividades  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6010891644492437993L;
	private Integer nbIdn;
     private TbPryActividades tbPryActividadPrevia;
     private TbPryActividades tbPryActividadSiguiente;
     private String vrAdtusuario;
     private Date dtAdtfecha;

    public String getVrAdtusuario() {
		return vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPryActividadesxactividades() {
    }

	public Integer getNbIdn() {
		return nbIdn;
	}

	public void setNbIdn(Integer nbIdn) {
		this.nbIdn = nbIdn;
	}

	public TbPryActividades getTbPryActividadPrevia() {
		return tbPryActividadPrevia;
	}

	public void setTbPryActividadPrevia(TbPryActividades tbPryActividadPrevia) {
		this.tbPryActividadPrevia = tbPryActividadPrevia;
	}

	public TbPryActividades getTbPryActividadSiguiente() {
		return tbPryActividadSiguiente;
	}

	public void setTbPryActividadSiguiente(TbPryActividades tbPryActividadSiguiente) {
		this.tbPryActividadSiguiente = tbPryActividadSiguiente;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public TbPryActividadesxactividades(Integer nbIdn,
			TbPryActividades tbPryActividadPrevia,
			TbPryActividades tbPryActividadSiguiente) {
		super();
		this.nbIdn = nbIdn;
		this.tbPryActividadPrevia = tbPryActividadPrevia;
		this.tbPryActividadSiguiente = tbPryActividadSiguiente;
	}
    
}


