package co.edu.udea.proyectointegrador.dto;
// Generated Oct 10, 2013 10:28:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryPermisosxestados generated by hbm2java
 */
public class TbPryPermisosxestados  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbPryEstados tbPryEstados;
     private TbAdmPermisos tbAdmPermisos;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     
     public String getVrAdtusuario() {
		return vrAdtusuario;
	}


	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}


	public Date getDtAdtfecha() {
		return dtAdtfecha;
	}


	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}


	

	
    public TbPryPermisosxestados() {
    }

	
    public TbPryPermisosxestados(Integer nbIdn, TbPryEstados tbPryEstados, TbAdmPermisos tbAdmPermisos) {
        this.nbIdn = nbIdn;
        this.tbPryEstados = tbPryEstados;
        this.tbAdmPermisos = tbAdmPermisos;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbPryEstados getTbPryEstados() {
        return this.tbPryEstados;
    }
    
    public void setTbPryEstados(TbPryEstados tbPryEstados) {
        this.tbPryEstados = tbPryEstados;
    }
    public TbAdmPermisos getTbAdmPermisos() {
        return this.tbAdmPermisos;
    }
    
    public void setTbAdmPermisos(TbAdmPermisos tbAdmPermisos) {
        this.tbAdmPermisos = tbAdmPermisos;
    }
 



}


