package co.edu.udea.proyectointegrador.dto;

import java.util.Date;
// Generated Oct 10, 2013 10:28:13 AM by Hibernate Tools 3.2.1.GA



/**
 * TbPryRolesxpermisosestadosproyecto generated by hbm2java
 */
public class TbPryRolesxpermisosestadosproyecto  implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String vrAdtusuario;
    private Date dtAdtfecha;
     private Integer nbIdn;
     private TbPryPermisosxestados tbPryPermisosxestados;
     private TbAdmRoles tbAdmRoles;

    public TbPryRolesxpermisosestadosproyecto() {
    }

    public TbPryRolesxpermisosestadosproyecto(Integer nbIdn, TbPryPermisosxestados tbPryPermisosxestados, TbAdmRoles tbAdmRoles) {
       this.nbIdn = nbIdn;
       this.tbPryPermisosxestados = tbPryPermisosxestados;
       this.tbAdmRoles = tbAdmRoles;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbPryPermisosxestados getTbPryPermisosxestados() {
        return this.tbPryPermisosxestados;
    }
    
    public void setTbPryPermisosxestados(TbPryPermisosxestados tbPryPermisosxestados) {
        this.tbPryPermisosxestados = tbPryPermisosxestados;
    }
    public TbAdmRoles getTbAdmRoles() {
        return this.tbAdmRoles;
    }
    
    public void setTbAdmRoles(TbAdmRoles tbAdmRoles) {
        this.tbAdmRoles = tbAdmRoles;
    }

	public String getVrAdtusuario() {
		return vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}




}


