package co.edu.udea.proyectointegrador.dto;
// Generated Jan 22, 2014 7:26:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryEntregablexactividad generated by hbm2java
 */
public class TbPryEntregablexactividad  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3824086299971796662L;
	private Integer nbIdn;
     private TbPryActividades tbPryActividades;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     private String vrNombre;
     private String vrDescripcion;
    
    public TbPryEntregablexactividad() {
    }

	
    public TbPryEntregablexactividad(TbPryActividades tbPryActividades, String vrAdtusuario, Date dtAdtfecha, String vrNombre, String vrDescripcion) {
        this.tbPryActividades = tbPryActividades;
        this.vrAdtusuario = vrAdtusuario;
        this.dtAdtfecha = dtAdtfecha;
        this.vrNombre = vrNombre;
        this.vrDescripcion = vrDescripcion;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbPryActividades getTbPryActividades() {
        return this.tbPryActividades;
    }
    
    public void setTbPryActividades(TbPryActividades tbPryActividades) {
        this.tbPryActividades = tbPryActividades;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
    public String getVrNombre() {
        return this.vrNombre;
    }
    
    public void setVrNombre(String vrNombre) {
        this.vrNombre = vrNombre;
    }
    public String getVrDescripcion() {
        return this.vrDescripcion;
    }
    
    public void setVrDescripcion(String vrDescripcion) {
        this.vrDescripcion = vrDescripcion;
    }
  



}


