package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryEntregables generated by hbm2java
 */
public class TbPryEntregables  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbPryActividades tbPryActividades;
     private String vrComentarioparticipante;
     private byte[] blobAdjunto;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     private String vrNombre;
     private String vrComentarioprofesor;

    public TbPryEntregables() {
    }
    
    public String getVrNombre() {
		return vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public TbPryEntregables(TbPryActividades tbPryActividades, String vrComentarioparticipante, byte[] blobAdjunto, String vrAdtusuario, Date dtAdtfecha, String vrComentarioprofesor) {
       this.tbPryActividades = tbPryActividades;
       this.vrComentarioparticipante = vrComentarioparticipante;
       this.blobAdjunto = blobAdjunto;
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
       this.vrComentarioprofesor = vrComentarioprofesor;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbPryActividades getTbPryActividades() {
        return this.tbPryActividades;
    }
    
    public void setTbPryActividades(TbPryActividades tbPryActividades) {
        this.tbPryActividades = tbPryActividades;
    }
    public String getVrComentarioparticipante() {
        return this.vrComentarioparticipante;
    }
    
    public void setVrComentarioparticipante(String vrComentarioparticipante) {
        this.vrComentarioparticipante = vrComentarioparticipante;
    }
    public byte[] getBlobAdjunto() {
        return this.blobAdjunto;
    }
    
    public void setBlobAdjunto(byte[] blobAdjunto) {
        this.blobAdjunto = blobAdjunto;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
    public String getVrComentarioprofesor() {
        return this.vrComentarioprofesor;
    }
    
    public void setVrComentarioprofesor(String vrComentarioprofesor) {
        this.vrComentarioprofesor = vrComentarioprofesor;
    }




}


