package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryActividades generated by hbm2java
 */
public class TbPryActividades  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbPryObjetivosespecificos tbPryObjetivosespecificos;
     private TbPryEstadosactividad tbPryEstadosactividad;
     private String vrNombreactividad;
     private String vrDescripcionactividad;
     private Date dtFechacreacion;
     private Date dtFechafinal;
     private long nbPorcentajesobreactividad;
     private String vrAdtusuario;
     private Date dtAdtfecha;
     private String vrJustificacioncancelacion;
     private String vrJustificacionsuspencion;
     private Date dtFechainicial;
   
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

   
     


	public TbPryActividades() {
    }

	
    public String getVrDescripcionactividad() {
		return vrDescripcionactividad;
	}


	public void setVrDescripcionactividad(String vrDescripcionactividad) {
		this.vrDescripcionactividad = vrDescripcionactividad;
	}


	public TbPryActividades(TbPryObjetivosespecificos tbPryObjetivosespecificos, TbPryEstadosactividad tbPryEstadosactividad, String vrNombreactividad, Date dtFechacreacion, Date dtFechafinal, long nbPorcentajesobreactividad, String vrAdtusuario, Date dtAdtfecha, Date dtFechainicial, String vrDescripcionActividad) {
        this.tbPryObjetivosespecificos = tbPryObjetivosespecificos;
        this.tbPryEstadosactividad = tbPryEstadosactividad;
        this.vrNombreactividad = vrNombreactividad;
        this.dtFechacreacion = dtFechacreacion;
        this.dtFechafinal = dtFechafinal;
        this.nbPorcentajesobreactividad = nbPorcentajesobreactividad;
        this.vrAdtusuario = vrAdtusuario;
        this.dtAdtfecha = dtAdtfecha;
        this.dtFechainicial = dtFechainicial;
        this.vrDescripcionactividad = vrDescripcionActividad;
    }
    
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbPryObjetivosespecificos getTbPryObjetivosespecificos() {
        return this.tbPryObjetivosespecificos;
    }
    
    public void setTbPryObjetivosespecificos(TbPryObjetivosespecificos tbPryObjetivosespecificos) {
        this.tbPryObjetivosespecificos = tbPryObjetivosespecificos;
    }
    public TbPryEstadosactividad getTbPryEstadosactividad() {
        return this.tbPryEstadosactividad;
    }
    
    public void setTbPryEstadosactividad(TbPryEstadosactividad tbPryEstadosactividad) {
        this.tbPryEstadosactividad = tbPryEstadosactividad;
    }
    public String getVrNombreactividad() {
        return this.vrNombreactividad;
    }
    
    public void setVrNombreactividad(String vrNombreactividad) {
        this.vrNombreactividad = vrNombreactividad;
    }
    public Date getDtFechacreacion() {
        return this.dtFechacreacion;
    }
    
    public void setDtFechacreacion(Date dtFechacreacion) {
        this.dtFechacreacion = dtFechacreacion;
    }
    public Date getDtFechafinal() {
        return this.dtFechafinal;
    }
    
    public void setDtFechafinal(Date dtFechafinal) {
        this.dtFechafinal = dtFechafinal;
    }
    public long getNbPorcentajesobreactividad() {
        return this.nbPorcentajesobreactividad;
    }
    
    public void setNbPorcentajesobreactividad(long nbPorcentajesobreactividad) {
        this.nbPorcentajesobreactividad = nbPorcentajesobreactividad;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
    
    public String getVrJustificacioncancelacion() {
        return this.vrJustificacioncancelacion;
    }
    
    public void setVrJustificacioncancelacion(String vrJustificacioncancelacion) {
        this.vrJustificacioncancelacion = vrJustificacioncancelacion;
    }
    public String getVrJustificacionsuspencion() {
        return this.vrJustificacionsuspencion;
    }
    
    public void setVrJustificacionsuspencion(String vrJustificacionsuspencion) {
        this.vrJustificacionsuspencion = vrJustificacionsuspencion;
    }
    public Date getDtFechainicial() {
        return this.dtFechainicial;
    }
    
    public void setDtFechainicial(Date dtFechainicial) {
        this.dtFechainicial = dtFechainicial;
    }
  



}


