package co.edu.udea.proyectointegrador.dto;

// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * TbPryTiposproyecto generated by hbm2java Esta clase representa un tipo de
 * proyecto.
 */
public class TbPryTiposproyecto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Identificador unico del tipo de proyecto dentro de la base de datos
	 * */
	private Integer nbIdn;
	/**
	 * Nombre del tipo de proyecto
	 * */
	private String vrNombre;
	/**
	 * Campo de auditoria que contiene el login del ultimo usuario que modifico
	 * el registro de la base de datos.
	 * */
	private String vrAdtusuario;
	/**
	 * Fecha de la ultima modificacion realizada en el registro
	 * */
	private Date dtAdtfecha;
	
	public TbPryTiposproyecto() {
	}

	public TbPryTiposproyecto(String vrNombre, String vrAdtusuario,
			Date dtAdtfecha) {
		this.vrNombre = vrNombre;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	
	public Integer getNbIdn() {
		return this.nbIdn;
	}

	public void setNbIdn(Integer nbIdn) {
		this.nbIdn = nbIdn;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	
}
