package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryProyectos generated by hbm2java
 */
public class TbPryProyectos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbAdmUsuarios tbAdmUsuarios;
     private TbPryTiposproyecto tbPryTiposproyecto;
     private TbPryEstados tbPryEstados;
     private TbPryModalidades tbPryModalidades;
     private String vrNombreproyecto;
     private String vrObjetivogeneral;
     private Date dtFechainicial;
     private String vrAdtusuario;
     private String vrCalificacion;
     private String vrJustificacioncancelacion;
     private String vrJustificacionsuspencion;
     private String vrReconocimiento;
     private Date dtFechacreacion;
     private Date dtFechafinal;
     private Date dtAdtfecha;
    
    public TbPryProyectos() {
    }

	
    public TbPryProyectos(TbAdmUsuarios tbAdmUsuarios, TbPryTiposproyecto tbPryTiposproyecto, TbPryEstados tbPryEstados, TbPryModalidades tbPryModalidades, String vrNombreproyecto, String vrObjetivogeneral, Date dtFechainicial, String vrAdtusuario, Date dtFechacreacion, Date dtFechafinal, Date dtAdtfecha) {
        this.tbAdmUsuarios = tbAdmUsuarios;
        this.tbPryTiposproyecto = tbPryTiposproyecto;
        this.tbPryEstados = tbPryEstados;
        this.tbPryModalidades = tbPryModalidades;
        this.vrNombreproyecto = vrNombreproyecto;
        this.vrObjetivogeneral = vrObjetivogeneral;
        this.dtFechainicial = dtFechainicial;
        this.vrAdtusuario = vrAdtusuario;
        this.dtFechacreacion = dtFechacreacion;
        this.dtFechafinal = dtFechafinal;
        this.dtAdtfecha = dtAdtfecha;
    }
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbAdmUsuarios getTbAdmUsuarios() {
        return this.tbAdmUsuarios;
    }
    
    public void setTbAdmUsuarios(TbAdmUsuarios tbAdmUsuarios) {
        this.tbAdmUsuarios = tbAdmUsuarios;
    }
    public TbPryTiposproyecto getTbPryTiposproyecto() {
        return this.tbPryTiposproyecto;
    }
    
    public void setTbPryTiposproyecto(TbPryTiposproyecto tbPryTiposproyecto) {
        this.tbPryTiposproyecto = tbPryTiposproyecto;
    }
    public TbPryEstados getTbPryEstados() {
        return this.tbPryEstados;
    }
    
    public void setTbPryEstados(TbPryEstados tbPryEstados) {
        this.tbPryEstados = tbPryEstados;
    }
    public TbPryModalidades getTbPryModalidades() {
        return this.tbPryModalidades;
    }
    
    public void setTbPryModalidades(TbPryModalidades tbPryModalidades) {
        this.tbPryModalidades = tbPryModalidades;
    }
    public String getVrNombreproyecto() {
        return this.vrNombreproyecto;
    }
    
    public void setVrNombreproyecto(String vrNombreproyecto) {
        this.vrNombreproyecto = vrNombreproyecto;
    }
    public String getVrObjetivogeneral() {
        return this.vrObjetivogeneral;
    }
    
    public void setVrObjetivogeneral(String vrObjetivogeneral) {
        this.vrObjetivogeneral = vrObjetivogeneral;
    }
    public Date getDtFechainicial() {
        return this.dtFechainicial;
    }
    
    public void setDtFechainicial(Date dtFechainicial) {
        this.dtFechainicial = dtFechainicial;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public String getVrCalificacion() {
        return this.vrCalificacion;
    }
    
    public void setVrCalificacion(String vrCalificacion) {
        this.vrCalificacion = vrCalificacion;
    }
    public String getVrJustificacioncancelacion() {
        return this.vrJustificacioncancelacion;
    }
    
    public void setVrJustificacioncancelacion(String vrJustificacioncancelacion) {
        this.vrJustificacioncancelacion = vrJustificacioncancelacion;
    }
    public String getVrJustificacionsuspencion() {
        return this.vrJustificacionsuspencion;
    }
    
    public void setVrJustificacionsuspencion(String vrJustificacionsuspencion) {
        this.vrJustificacionsuspencion = vrJustificacionsuspencion;
    }
    public String getVrReconocimiento() {
        return this.vrReconocimiento;
    }
    
    public void setVrReconocimiento(String vrReconocimiento) {
        this.vrReconocimiento = vrReconocimiento;
    }
    public Date getDtFechacreacion() {
        return this.dtFechacreacion;
    }
    
    public void setDtFechacreacion(Date dtFechacreacion) {
        this.dtFechacreacion = dtFechacreacion;
    }
    public Date getDtFechafinal() {
        return this.dtFechafinal;
    }
    
    public void setDtFechafinal(Date dtFechafinal) {
        this.dtFechafinal = dtFechafinal;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
  



}


