package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryModalidades generated by hbm2java
 */
public class TbPryModalidades  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private String vrNombre;
     private String vrAdtusuario;
     private Date dtAdtfecha;
  
    public TbPryModalidades() {
    }

	
    public TbPryModalidades(String vrNombre, String vrAdtusuario, Date dtAdtfecha) {
        this.vrNombre = vrNombre;
        this.vrAdtusuario = vrAdtusuario;
        this.dtAdtfecha = dtAdtfecha;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public String getVrNombre() {
        return this.vrNombre;
    }
    
    public void setVrNombre(String vrNombre) {
        this.vrNombre = vrNombre;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }
  



}


