package co.edu.udea.proyectointegrador.dto;
// Generated Sep 9, 2013 7:13:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryAsesorxproyecto generated by hbm2java
 */
public class TbPryAsesorxproyecto  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbAdmUsuarios tbAdmUsuarios;
     private TbPryProyectos tbPryProyectos;
     private String vrAdtusuario;
     private Date dtAdtfecha;

    public TbPryAsesorxproyecto() {
    }

    public TbPryAsesorxproyecto(TbAdmUsuarios tbAdmUsuarios, TbPryProyectos tbPryProyectos, String vrAdtusuario, Date dtAdtfecha) {
       this.tbAdmUsuarios = tbAdmUsuarios;
       this.tbPryProyectos = tbPryProyectos;
       this.vrAdtusuario = vrAdtusuario;
       this.dtAdtfecha = dtAdtfecha;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbAdmUsuarios getTbAdmUsuarios() {
        return this.tbAdmUsuarios;
    }
    
    public void setTbAdmUsuarios(TbAdmUsuarios tbAdmUsuarios) {
        this.tbAdmUsuarios = tbAdmUsuarios;
    }
    public TbPryProyectos getTbPryProyectos() {
        return this.tbPryProyectos;
    }
    
    public void setTbPryProyectos(TbPryProyectos tbPryProyectos) {
        this.tbPryProyectos = tbPryProyectos;
    }
    public String getVrAdtusuario() {
        return this.vrAdtusuario;
    }
    
    public void setVrAdtusuario(String vrAdtusuario) {
        this.vrAdtusuario = vrAdtusuario;
    }
    public Date getDtAdtfecha() {
        return this.dtAdtfecha;
    }
    
    public void setDtAdtfecha(Date dtAdtfecha) {
        this.dtAdtfecha = dtAdtfecha;
    }




}


