package co.edu.udea.proyectointegrador.dto;
// Generated Oct 10, 2013 10:28:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPryPermisosxestadosactividad generated by hbm2java
 */
public class TbPryPermisosxestadosactividad  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nbIdn;
     private TbAdmPermisos tbAdmPermisos;
     private TbPryEstadosactividad tbPryEstadosactividad;
 
     private String vrAdtusuario;
     private Date dtAdtfecha;
     
    public String getVrAdtusuario() {
		return vrAdtusuario;
	}


	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}


	public Date getDtAdtfecha() {
		return dtAdtfecha;
	}


	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}


	public TbPryPermisosxestadosactividad() {
    }

	
    public TbPryPermisosxestadosactividad(Integer nbIdn, TbAdmPermisos tbAdmPermisos, TbPryEstadosactividad tbPryEstadosactividad) {
        this.nbIdn = nbIdn;
        this.tbAdmPermisos = tbAdmPermisos;
        this.tbPryEstadosactividad = tbPryEstadosactividad;
    }
   
    public Integer getNbIdn() {
        return this.nbIdn;
    }
    
    public void setNbIdn(Integer nbIdn) {
        this.nbIdn = nbIdn;
    }
    public TbAdmPermisos getTbAdmPermisos() {
        return this.tbAdmPermisos;
    }
    
    public void setTbAdmPermisos(TbAdmPermisos tbAdmPermisos) {
        this.tbAdmPermisos = tbAdmPermisos;
    }
    public TbPryEstadosactividad getTbPryEstadosactividad() {
        return this.tbPryEstadosactividad;
    }
    
    public void setTbPryEstadosactividad(TbPryEstadosactividad tbPryEstadosactividad) {
        this.tbPryEstadosactividad = tbPryEstadosactividad;
    }
   



}


